spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/syncup
spring.datasource.username=uni

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false